# Generated by Django 4.1.3 on 2022-11-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nature', 'n'), ('adventure', 'a'), ('people', 'p')], max_length=255)),
                ('art_image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
